## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.4
  - nightly

arch:
  - amd64
  - x86

branches:
  only:
    - master
    - dev
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

jobs:
  #allow_failures:
  #  - julia: nightly
  #fast_finish: true
  exclude:
    - os: osx
      arch: x86
    - os: windows
      arch: x86
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      arch: amd64
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
