## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux

julia:
  - nightly

arch:
  - amd64

notifications:
  email: false

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
