name = "ArraysOfArrays"
uuid = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
version = "0.7.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[extensions]
ArraysOfArraysAdaptExt = "Adapt"
ArraysOfArraysChainRulesCoreExt = "ChainRulesCore"
ArraysOfArraysFixedSizeArraysExt = "FixedSizeArrays"
ArraysOfArraysMooncakeExt = "Mooncake"
ArraysOfArraysStaticArraysCoreExt = "StaticArraysCore"

[compat]
Adapt = "1, 2, 3, 4"
ChainRulesCore = "1"
FixedSizeArrays = "1"
Mooncake = "0.5"
StaticArraysCore = "1"
Statistics = "1"
julia = "1.10"
